# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use the official Node.js image
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Set environment variables
# These should be overridden by the user at runtime
ENV JIRA_INSTANCE_URL=https://your-instance.atlassian.net
ENV JIRA_USER_EMAIL=your-email@company.com
ENV JIRA_API_KEY=your-api-token

# Expose any necessary ports (not mentioned in the README, but typically needed for servers)
# EXPOSE 3000

# Command to run the MCP server
ENTRYPOINT ["node", "index.js"]
